import React, { createContext, useContext, useState, useEffect } from 'react';
import { Language } from '../types';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  dir: 'ltr' | 'rtl';
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // App Brand
    appName: 'Eco Challenge',
    appVersion: 'v2.0',
    appSubtitle: '90s Arcade Green Action',

    // Navigation Tabs
    navQuests: 'Quests',
    navSquads: 'Squads',
    navKarin: 'Karin AI',
    navFeed: 'Media Feed',
    navStore: 'Store',
    navSettings: 'Settings',

    // Top Header & Stats
    streakLabel: 'Streak',
    streakDays: 'Days',
    scoreLabel: 'Eco Points',
    pts: 'PTS',
    qaButton: 'QA Diagnostic',
    dailyCheckInTitle: 'Daily Check-in Rewards',
    dailyCheckInSubtitle: 'Claim free Eco Points once every 24 hours & build your visual streak!',
    claimDailyBtn: 'Claim Daily Reward',
    alreadyClaimedToday: 'Checked in today! Streak active',
    nextCheckInIn: 'Next reward available in',
    streakTrackTitle: '7-Day Reward Ladder',
    simulateNextDay: 'Simulate +24h (Next Day)',
    consecutiveDays: 'consecutive days',
    dayX: 'Day',
    claimed: 'Claimed',
    locked: 'Locked',
    claimNow: 'Claim Now',
    dailyEcoTipTitle: 'Daily Eco-Tip',
    dailyEcoTipSubtitle: 'Inspiring environmental facts & quick green actions',
    refreshTip: 'Refresh Tip',
    didYouKnow: 'DID YOU KNOW?',
    takeAction: 'GREEN ACTION:',

    // Auth Landing
    welcomeTitle: 'SAVE THE PLANET, WARRIOR!',
    welcomeSubtitle: 'Join the retro 90s eco-arcade movement. Complete daily green tasks, earn points, verify with Karin AI, and unite with your eco-squad!',
    signInGoogle: 'Sign in with Google',
    continueGuest: 'Continue as Guest',
    guestNotice: 'Guest Mode: Your progress is currently stored locally. Link your account anytime in Settings to enable cloud sync!',
    accountBannedTitle: 'ACCOUNT BANNED',
    accountBannedDesc: 'Your account has been restricted due to violation of community safety rules (NSFW/Violence). Contact Eco Safety Support.',

    // Quests Tab
    questsTitle: 'DAILY ECO QUESTS',
    questsSubtitle: 'Complete tasks, snap evidence, and get verified by Karin AI!',
    filterAll: 'All Quests',
    filterWaste: 'Waste',
    filterWater: 'Water',
    filterEnergy: 'Energy',
    filterNature: 'Nature',
    filterCommunity: 'Community',
    questStatusCompleted: 'VERIFIED',
    questStatusOpen: 'OPEN QUEST',
    questActionVerify: 'Submit Proof',
    questDetailTitle: 'Quest Briefing',
    questTips: 'Karin AI Verification Tips:',
    questReward: 'Reward:',
    submitEvidenceTitle: 'Submit Photo Evidence',
    takeOrUploadPhoto: 'Select or Take Photo Proof',
    cameraButton: 'Open Camera / File',
    userNotePlaceholder: 'Add a brief note for Karin (e.g. Planted basil in our garden!)...',
    karinAnalyzing: 'Karin AI is inspecting your proof...',
    verifySuccessTitle: 'MISSION APPROVED!',
    verifyFailTitle: 'VERIFICATION PENDING',
    closeBtn: 'Close',
    claimRewardBtn: 'Collect Points!',
    trackInGauge: 'Track in Gauge',
    trackedInGauge: 'Tracking',
    activeQuestGaugeTitle: 'CURRENT ACTIVE QUEST',

    // Squads Tab
    squadsTitle: 'ECO SQUADS & CHAT',
    noSquadsJoined: 'You have not joined any Squad yet!',
    noSquadsPrompt: 'Find an eco squad in the directory or create your own!',
    joinGroupBtn: 'Join Group',
    createGroupBtn: 'Create Squad',
    showOtherGroupsBtn: 'Show Other Groups',
    activeSquadLabel: 'Active Squad:',
    squadMembersCount: 'members',
    squadTotalPoints: 'Squad Score:',
    squadRoleLeader: 'Leader',
    squadRoleCoLeader: 'Co-Leader',
    squadRoleMember: 'Member',
    chatPlaceholder: 'Type a message to squad...',
    sendVoiceNote: 'Voice Note',
    recordingVoice: 'Recording voice note... tap to finish',
    stopRecording: 'Send Audio',
    cancelRecording: 'Cancel',
    sendPhoto: 'Send Photo',
    leaderMute: 'Mute Member',
    leaderUnmute: 'Unmute',
    leaderKick: 'Kick from Squad',
    memberMutedNotice: 'You are currently muted in this squad by the leader.',
    shareSquadCode: 'Invite Code:',
    viewQR: 'Show QR Code',
    qrTitle: 'Squad QR Invite',
    scanQR: 'Scan QR',

    // Top Squads Leaderboards
    topSquadsTabBtn: 'Top Squads',
    squadChatTabBtn: 'Squad Chat',
    topSquadsTitle: 'TOP SQUADS LEADERBOARD',
    topSquadsSubtitle: 'Competitive global rankings & retro arcade badges',
    rankHeader: 'Rank',
    squadHeader: 'Squad',
    scoreHeader: 'Score',
    badgesHeader: 'Retro Badges',
    timeframeAllTime: 'All-Time',
    timeframeWeekly: 'Weekly League',
    timeframeSprint: 'Eco Sprint',
    refreshLeaderboard: 'Refresh Rankings',
    loadingRankings: 'Computing leaderboard rankings...',
    switchToSquad: 'Open Chat',
    joinFromLeaderboard: 'Join Squad',
    squadRankPrefix: 'RANK',
    pointsEarnedThisWeek: 'pts this week',
    yourSquadTag: 'YOUR SQUAD',

    // Discovery Directory Modal
    directoryTitle: 'JOIN SQUAD DIRECTORY',
    directorySubtitle: 'Browse all registered public & private eco-squads',
    searchSquadPlaceholder: 'Search squad by name or tag...',
    tabAllGroups: 'All Groups',
    tabPublicGroups: 'Public',
    tabPrivateGroups: 'Private (Passcode)',
    tabJoinByCode: 'Join by Code',
    enterCodePrompt: 'Enter 8-digit squad code (e.g. ECO-TREE-88):',
    joinBtn: 'Join Instantly',
    unlockBtn: 'Enter Password',
    privateSquadModalTitle: 'Private Squad Verification',
    enterPasswordPrompt: 'This squad is password-protected. Enter the squad access key:',
    passwordPlaceholder: 'Enter group password...',
    incorrectPassword: 'Incorrect password! Ask your squad leader.',
    alreadyJoinedBadge: 'ALREADY JOINED',

    // Create Group Modal
    createSquadTitle: 'CREATE NEW ECO SQUAD',
    groupNameLabel: 'Squad Name (AI Moderated):',
    groupNamePlaceholder: 'e.g., Solar Saviors 90s',
    groupDescLabel: 'Mission Description:',
    groupDescPlaceholder: 'Describe your squad goal (e.g. Clean the beach every Sunday)...',
    groupPrivacyLabel: 'Squad Privacy Mode:',
    groupPrivacyPublic: 'Public (Anyone can discover & join)',
    groupPrivacyPrivate: 'Private (Requires password)',
    groupPasswordLabel: 'Set Squad Password:',
    groupPasswordPlaceholder: 'Secret password for invites...',
    createSquadSubmit: 'Create Squad Now!',
    aiModerating: 'AI is checking group name...',
    groupNameRejected: 'Group name rejected by AI moderator:',

    // Karin AI Mentor Tab
    karinTitle: 'KARIN AI ECO-MENTOR',
    karinSubtitle: 'Your 90s cartoon guide for green tips, advice, and eco-auditing',
    karinWelcome: 'Hey Eco Warrior! I am Karin, your personal green mentor! Ask me anything about zero-waste, tree planting, energy saving, or upload a photo of an item you want to recycle!',
    karinInputPlaceholder: 'Ask Karin anything eco-friendly...',
    karinSendBtn: 'Send',
    karinQuick1: '🌱 How to start kitchen composting?',
    karinQuick2: '⚡ 3 easiest ways to save electricity?',
    karinQuick3: '♻️ Can this plastic bottle be upcycled?',
    karinQuick4: '🌳 How do I plant a tree correctly?',
    karinQuick5: '💧 Top water saving hacks?',
    karinUploadPhoto: 'Photo for Karin',
    karinClearChat: 'Reset Chat',
    karinThinking: 'Karin is thinking... 🌱',
    karinListen: 'Listen',
    karinStopVoice: 'Stop',
    karinVoiceCommands: 'Voice Commands',
    karinVoiceListening: 'Listening to voice command...',
    karinVoiceHint: 'Say an eco question or "Clear chat", "Save energy", "Compost", "Plant tree"...',
    karinVoiceUnsupported: 'Speech recognition is not supported in this browser',
    karinVoiceAutoSpeakOn: 'Auditory voice answers: ON',
    karinVoiceAutoSpeakOff: 'Auditory voice answers: OFF',
    karinVoiceListeningStop: 'Stop Voice',
    karinVoiceCommandRecognized: 'Voice Command:',
    karinResetAuditory: 'Chat has been reset! Ready for your eco missions!',

    // Media Feed Tab
    feedTitle: 'COMMUNITY MEDIA FEED',
    feedSubtitle: 'Real eco-actions from warriors around the world (AI Safety Shield Active)',
    postActionBtn: 'Post Eco Action',
    likeBtn: 'Cheer',
    flagPostBtn: 'Report',
    postModalTitle: 'Share Your Eco Action',
    postCaptionPlaceholder: 'Tell the world what green action you completed...',
    safetyShieldNotice: 'Protected by Gemini AI Safety Shield. Explicit/harmful content triggers an immediate permanent account ban.',
    publishPostBtn: 'Publish to Community',
    moderatingPost: 'AI Safety Shield checking content...',

    // Store Tab
    storeTitle: 'RETRO ECO STORE',
    storeSubtitle: 'Spend your hard-earned Eco Points on pixel avatars & badges!',
    yourBalance: 'Your Balance:',
    filterAvatars: 'Avatars',
    filterBadges: 'Badges',
    buyBtn: 'Buy for',
    equipBtn: 'Equip',
    equippedBadge: 'EQUIPPED',
    notEnoughPoints: 'Not enough points! Complete more Karin Quests.',

    // Settings Tab
    settingsTitle: 'SETTINGS & PROFILE',
    profileHeader: 'WARRIOR PROFILE',
    displayNameLabel: 'Display Name:',
    saveProfileBtn: 'Save Changes',
    avatarSelection: 'Choose Avatar:',
    accountSection: 'ACCOUNT & CLOUD SYNC',
    guestStatus: 'Current Status: Guest Mode',
    cloudStatus: 'Current Status: Synced via Cloud (Supabase)',
    syncCloudBtn: 'Connect Cloud Account',
    languageSection: 'LANGUAGE / اللغة',
    switchToArabic: 'العربية (Arabic RTL)',
    switchToEnglish: 'English (LTR)',
    qaSection: 'QA AUTOMATION & DIAGNOSTICS',
    runDiagnosticsBtn: 'Open QA Test Suite',
    arcadeSoundTitle: '90s ARCADE SOUND EFFECTS',
    arcadeSoundSubtitle: 'Plays authentic 8-bit / 16-bit coin and blip audio effects upon completing actions',
    testCoinSound: 'Test Coin 🪙',
    testBlipSound: 'Test Blip ⚡',
    arcadeSoundEnabled: 'Sound Effects: ON',
    arcadeSoundDisabled: 'Sound Effects: MUTED',
    aboutSection: 'ABOUT / حول التطبيق',
    aboutApp: 'Eco Challenge v2.0 is a mobile-first 90s retro arcade web app with global Gemini AI safety moderation, designed to turn ecological stewardship into a safe, social, community-driven adventure.',
    credits: 'Engineered with Next.js, Supabase, Tailwind CSS, and Google Gemini AI.',
    resetDataBtn: 'Reset Demo Data',
  },
  ar: {
    // App Brand
    appName: 'تحدي البيئة',
    appVersion: 'v2.0',
    appSubtitle: 'أركيد التسعينات للعمل الأخضر',

    // Navigation Tabs
    navQuests: 'المهام',
    navSquads: 'الفرق',
    navKarin: 'كارين AI',
    navFeed: 'المجتمع',
    navStore: 'المتجر',
    navSettings: 'الإعدادات',

    // Top Header & Stats
    streakLabel: 'التتابع',
    streakDays: 'أيام',
    scoreLabel: 'نقاط البيئة',
    pts: 'نقطة',
    qaButton: 'فحص QA',
    dailyCheckInTitle: 'مكافآت تسجيل الدخول اليومي',
    dailyCheckInSubtitle: 'احصل على نقاط بيئية مجانية كل 24 ساعة وعزز سلسلتك المتواصلة!',
    claimDailyBtn: 'استلام المكافأة اليومية',
    alreadyClaimedToday: 'سجلت دخولك اليوم! السلسلة نشطة',
    nextCheckInIn: 'المكافأة القادمة تفتح بعد',
    streakTrackTitle: 'سلّم مكافآت الـ 7 أيام',
    simulateNextDay: 'محاكاة +24 ساعة (اليوم التالي)',
    consecutiveDays: 'أيام متتالية',
    dayX: 'اليوم',
    claimed: 'تم الاستلام',
    locked: 'مغلق',
    claimNow: 'استلم الآن',
    dailyEcoTipTitle: 'نصيحة بيئية يومية',
    dailyEcoTipSubtitle: 'حقائق بيئية ملهمة وخطوات خضراء سريعة',
    refreshTip: 'نصيحة جديدة',
    didYouKnow: 'هل تعلم؟',
    takeAction: 'خطوة خضراء:',

    // Auth Landing
    welcomeTitle: 'أنقذ الكوكب يا بطل البيئة!',
    welcomeSubtitle: 'انضم إلى حركة الأركيد البيئية بنمط التسعينات الكرتوني. أنجز المهام الخضراء، واكسب النقاط، واحصل على اعتماد كارين AI، واتحد مع فريقك البيئي!',
    signInGoogle: 'تسجيل الدخول عبر Google',
    continueGuest: 'المتابعة كضيف',
    guestNotice: 'وضع الضيف: يتم حفظ تقدمك محلياً على هذا الجهاز. يمكنك ربط حسابك في أي وقت من الإعدادات لمزامنة سحابية دائمة!',
    accountBannedTitle: 'تم حظر الحساب',
    accountBannedDesc: 'تم حظر حسابك لمخالفة معايير الأمان وسلامة المجتمع (محتوى غير لائق أو عنيف). تواصل مع فريق الأمان البيئي.',

    // Quests Tab
    questsTitle: 'مهام البيئة اليومية',
    questsSubtitle: 'أنجز المهام، والتقط الأدلة، واحصل على موافقة كارين الذكية!',
    filterAll: 'جميع المهام',
    filterWaste: 'النفايات',
    filterWater: 'المياه',
    filterEnergy: 'الطاقة',
    filterNature: 'الطبيعة',
    filterCommunity: 'المجتمع',
    questStatusCompleted: 'تم الاعتماد',
    questStatusOpen: 'مهمة متاحة',
    questActionVerify: 'إرسال الدليل',
    questDetailTitle: 'تفاصيل المهمة',
    questTips: 'نصائح كارين لاعتماد المهمة:',
    questReward: 'المكافأة:',
    submitEvidenceTitle: 'إرسال صورة الدليل',
    takeOrUploadPhoto: 'التقاط أو اختيار صورة إثبات',
    cameraButton: 'فتح الكاميرا / الملفات',
    userNotePlaceholder: 'أضف ملاحظة قصيرة لكارين (مثال: زرعنا شتلة نعناع في شرفتنا!)...',
    karinAnalyzing: 'كارين تفحص الصورة بدقة بالذكاء الاصطناعي...',
    verifySuccessTitle: 'تم قبول المهمة بنجاح!',
    verifyFailTitle: 'لم يتم اعتماد الدليل',
    closeBtn: 'إغلاق',
    claimRewardBtn: 'استلام النقاط!',
    trackInGauge: 'تتبع في المؤشر',
    trackedInGauge: 'جارٍ التتبع',
    activeQuestGaugeTitle: 'المهمة البيئية الحالية',

    // Squads Tab
    squadsTitle: 'الفرق البيئية والمحادثة',
    noSquadsJoined: 'أنت لم تنضم لأي فريق بيئي بعد!',
    noSquadsPrompt: 'ابحث عن فريق في دليل المجموعات أو أنشئ فريقك الخاص الآن!',
    joinGroupBtn: 'انضمام لجروب',
    createGroupBtn: 'إنشاء فريق',
    showOtherGroupsBtn: 'عرض باقي الفرق',
    activeSquadLabel: 'الفريق النشط:',
    squadMembersCount: 'عضو',
    squadTotalPoints: 'مجموع نقاط الفريق:',
    squadRoleLeader: 'قائد الفريق',
    squadRoleCoLeader: 'نائب القائد',
    squadRoleMember: 'عضو',
    chatPlaceholder: 'اكتب رسالة لأعضاء الفريق...',
    sendVoiceNote: 'تسجيل صوتي',
    recordingVoice: 'جارٍ تسجيل رسالة صوتية... اضغط للإنهاء',
    stopRecording: 'إرسال الصوت',
    cancelRecording: 'إلغاء',
    sendPhoto: 'إرسال صورة',
    leaderMute: 'كتم العضو',
    leaderUnmute: 'إلغاء الكتم',
    leaderKick: 'طرد من الفريق',
    memberMutedNotice: 'تم كتمك في هذا الفريق بواسطة القائد.',
    shareSquadCode: 'رمز الدعوة:',
    viewQR: 'عرض رمز QR',
    qrTitle: 'رمز QR لدعوة الفريق',
    scanQR: 'مسح QR',

    // Top Squads Leaderboards
    topSquadsTabBtn: 'لوحة الأبطال',
    squadChatTabBtn: 'محادثة الفريق',
    topSquadsTitle: 'لوحة شرف أفضل الفرق',
    topSquadsSubtitle: 'التصنيف التنافسي للفرق والشارات الاستثنائية',
    rankHeader: 'الترتيب',
    squadHeader: 'الفريق',
    scoreHeader: 'النقاط',
    badgesHeader: 'الشارات',
    timeframeAllTime: 'كل الأوقات',
    timeframeWeekly: 'الدوري الأسبوعي',
    timeframeSprint: 'السباق السريع',
    refreshLeaderboard: 'تحديث الترتيب',
    loadingRankings: 'جارٍ حساب نتائج المتصدرين...',
    switchToSquad: 'فتح المحادثة',
    joinFromLeaderboard: 'انضمام للفريق',
    squadRankPrefix: 'المركز',
    pointsEarnedThisWeek: 'نقطة هذا الأسبوع',
    yourSquadTag: 'فريقك الحالي',

    // Discovery Directory Modal
    directoryTitle: 'دليل استكشاف الفرق',
    directorySubtitle: 'تصفح جميع الفرق البيئية المسجلة العامة والخاصة',
    searchSquadPlaceholder: 'ابحث عن فريق بالاسم أو الشعار...',
    tabAllGroups: 'كل الفرق',
    tabPublicGroups: 'عامة (دخول فوري)',
    tabPrivateGroups: 'خاصة (كلمة مرور)',
    tabJoinByCode: 'انضمام برمز الدعوة',
    enterCodePrompt: 'أدخل رمز الفريق المكون من 8 أحرف (مثال: ECO-TREE-88):',
    joinBtn: 'انضمام فوري',
    unlockBtn: 'إدخال كلمة المرور',
    privateSquadModalTitle: 'فريق خاص محمي',
    enterPasswordPrompt: 'هذا الفريق محمي بكلمة سر. أدخل مفتاح المرور للانضمام:',
    passwordPlaceholder: 'أدخل كلمة مرور الفريق...',
    incorrectPassword: 'كلمة المرور غير صحيحة! اطلبها من قائد الفريق.',
    alreadyJoinedBadge: 'منضم بالفعل',

    // Create Group Modal
    createSquadTitle: 'إنشاء فريق بيئي جديد',
    groupNameLabel: 'اسم الفريق (مراقب بالذكاء الاصطناعي):',
    groupNamePlaceholder: 'مثال: حماة الأرض التسعينات',
    groupDescLabel: 'وصف المهمة والهدف:',
    groupDescPlaceholder: 'ما هدف الفريق (مثال: تنظيف الشواطئ كل جمعة)...',
    groupPrivacyLabel: 'نوع خصوصية الفريق:',
    groupPrivacyPublic: 'عام (يمكن للجميع استكشافه والانضمام)',
    groupPrivacyPrivate: 'خاص (يتطلب كلمة مرور)',
    groupPasswordLabel: 'تعيين كلمة مرور الفريق:',
    groupPasswordPlaceholder: 'كلمة السر السرية للمدعوين...',
    createSquadSubmit: 'إنشاء الفريق الآن!',
    aiModerating: 'جارٍ فحص الاسم بالذكاء الاصطناعي...',
    groupNameRejected: 'تم رفض اسم الفريق بواسطة الرقيب الذكي:',

    // Karin AI Mentor Tab
    karinTitle: 'مرشدتك الذكية كارين',
    karinSubtitle: 'شخصيتك الكرتونية لنصائح الاستدامة والتدقيق البيئي',
    karinWelcome: 'مرحباً يا بطل البيئة! أنا كارين، مرشدتك الخضراء! اسألني عن أي شيء يخص إعادة التدوير، أو الزراعة، أو ترشيد الكهرباء، أو ارفع صورة لغرض تريد معرفة طريقة تدويره!',
    karinInputPlaceholder: 'اسأل كارين أي سؤال بيئي...',
    karinSendBtn: 'إرسال',
    karinQuick1: '🌱 كيف أبدأ صناعة السماد العضوي المنزلي؟',
    karinQuick2: '⚡ ما هي أسهل 3 طرق لتوفير الكهرباء؟',
    karinQuick3: '♻️ هل يمكن إعادة تدوير هذه الزجاجة البلاستيكية؟',
    karinQuick4: '🌳 كيف أزرع شجرة بالطريقة الصحيحة؟',
    karinQuick5: '💧 ما هي أهم حيل توفير المياه؟',
    karinUploadPhoto: 'صورة لكارين',
    karinClearChat: 'إعادة ضبط المحادثة',
    karinThinking: 'كارين تفكر... 🌱',
    karinListen: 'استمع لكارين',
    karinStopVoice: 'إيقاف الصوت',
    karinVoiceCommands: 'الأوامر الصوتية',
    karinVoiceListening: 'جارٍ الاستماع لأمرك الصوتي...',
    karinVoiceHint: 'تحدث بسؤالك البيئي أو قل "امسح المحادثة"، "توفير الكهرباء"، "صناعة السماد"، "زراعة شجرة"...',
    karinVoiceUnsupported: 'التعرف على الصوت غير مدعوم في هذا المتصفح',
    karinVoiceAutoSpeakOn: 'الرد الصوتي التلقائي: مفعّل',
    karinVoiceAutoSpeakOff: 'الرد الصوتي التلقائي: معطّل',
    karinVoiceListeningStop: 'إيقاف الاستماع',
    karinVoiceCommandRecognized: 'الأمر الصوتي:',
    karinResetAuditory: 'تمت إعادة ضبط المحادثة! جاهزة لمهامك البيئية الخضراء!',

    // Media Feed Tab
    feedTitle: 'معرض المجتمع البيئي',
    feedSubtitle: 'مشاركات حقيقية من أبطال البيئة حول العالم (درع الأمان AI مفعّل)',
    postActionBtn: 'نشر عمل بيئي',
    likeBtn: 'تشجيع',
    flagPostBtn: 'إبلاغ',
    postModalTitle: 'شارك عملك البيئي مع العالم',
    postCaptionPlaceholder: 'اكتب وصفاً للعمل البيئي الأخضر الذي قمت به اليوم...',
    safetyShieldNotice: 'محمي بدرع أمان Gemini AI. نشر أي محتوى عنيف أو خادش للحياء يؤدي للحظر الفوري والدائم للحساب.',
    publishPostBtn: 'نشر في المجتمع',
    moderatingPost: 'درع الأمان AI يفحص المنشور...',

    // Store Tab
    storeTitle: 'متجر الأركيد البيئي',
    storeSubtitle: 'استبدل نقاطك البيئية بشخصيات بكسل وأوسمة ريترو نادرة!',
    yourBalance: 'رصيدك الحالي:',
    filterAvatars: 'الشخصيات',
    filterBadges: 'الأوسمة',
    buyBtn: 'شراء بـ',
    equipBtn: 'تجهيز',
    equippedBadge: 'مجهّز حالياً',
    notEnoughPoints: 'النقاط غير كافية! أنجز المزيد من مهام كارين.',

    // Settings Tab
    settingsTitle: 'الإعدادات والملف الشخصي',
    profileHeader: 'ملف المحارب البيئي',
    displayNameLabel: 'الاسم المعروض:',
    saveProfileBtn: 'حفظ التعديلات',
    avatarSelection: 'اختر صورتك الرمزية:',
    accountSection: 'الحساب والمزامنة السحابية',
    guestStatus: 'الحالة الحالية: وضع الضيف (محلي)',
    cloudStatus: 'الحالة الحالية: متزامن سحابياً (Supabase)',
    syncCloudBtn: 'ربط حساب سحابي دائم',
    languageSection: 'اللغة / Language',
    switchToArabic: 'العربية (RTL)',
    switchToEnglish: 'English (LTR)',
    qaSection: 'الاختبار الشامل وأتمتة QA',
    runDiagnosticsBtn: 'فتح لوحة فحص QA الشاملة',
    arcadeSoundTitle: 'مؤثرات صوت الأركيد التسعينات',
    arcadeSoundSubtitle: 'تشغيل أصوات أركيد 8-bit و 16-bit نوستالجية (صوت العملة والنقرة) عند إنجاز الأعمال',
    testCoinSound: 'تجربة صوت العملة 🪙',
    testBlipSound: 'تجربة صوت النقرة ⚡',
    arcadeSoundEnabled: 'مؤثرات الصوت: مفعّلة',
    arcadeSoundDisabled: 'مؤثرات الصوت: مكتومة',
    aboutSection: 'حول التطبيق / About',
    aboutApp: 'تحدي البيئة v2.0 تطبيق ويب بنمط أركيد كرتوني من التسعينات مع درع أمان وحماية فوري بالذكاء الاصطناعي Gemini، يحول حماية البيئة إلى مغامرة اجتماعية آمنة وتنافسية ممتعة.',
    credits: 'مبني بأحدث تقنيات Next.js و Supabase و Tailwind CSS ونماذج Google Gemini AI.',
    resetDataBtn: 'إعادة تعيين البيانات التجريبية',
  },
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  dir: 'ltr',
  t: (key: string) => key,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('eco_challenge_lang');
    return saved === 'ar' || saved === 'en' ? saved : 'en';
  });

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  useEffect(() => {
    document.documentElement.setAttribute('dir', dir);
    document.documentElement.setAttribute('lang', language);
    localStorage.setItem('eco_challenge_lang', language);
  }, [language, dir]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, dir, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
